### ISSUE TITLE
Hi-res fix. causing indefinite stuck on both anapnoe and automatic111

### ISSUE THREAD

**Issue by excuse-me-just-minding-my-own-bussiness** [Linaqruf/sd-notebook-collection#33]
yep, it stuck. and happens _**almost**_ every time I use **Hi-res fix**, it usually happens when finalizing the image like 97% finish on UI and 100% completed process on colab, this problem appeared 2 days ago I guess when the _adetailer& CN reference_ was added, the interrupt/skip also broken when using hi-res (there no point clicking it though knowing using hi-res already makes progress stuck), the usual stuff happens before this still saved the images to drive output, but this one isn't, that all I know, hope there is a way to fix it.

- tested it again, it often work again by waiting for 10minutes+ or so
- probable storing issues?
- when that happen the finished images wont show on UI after result (_it common though_) 
- seems like higher resolution cause the big part of the problem (using 1024x512 with 2x hres upscale are enough to trigger the problem, no lowram args)

**Comment by Linaqruf** [comment]
Hi, please refer to this issue, https://github.com/Linaqruf/sd-notebook-collection/issues/30
