### ISSUE TITLE
Detected that PyTorch and torchvision were compiled with different CUDA versions

### ISSUE THREAD

**Issue by misdi** [Linaqruf/sd-notebook-collection#36]
How to fix this error:

RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

**Comment by Linaqruf** [comment]
Hi, are you using Colab Pro?

**Comment by misdi** [comment]
no, I'm using [cagliostro-colab-ui.ipynb](https://github.com/Linaqruf/sd-notebook-collection/blob/main/cagliostro-colab-ui.ipynb)

**Comment by misdi** [comment]
problem solved.
I must clean up the folder and unpacking. 

thank you.
