### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by katsuki-uuu** [Linaqruf/sd-notebook-collection#44]
Hello.
I get the following error in the Start Cagliostro Colab UI. What is the cause?

AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 
'get_sort_keys'
Creating model from config: /content/cagliostro-colab-ui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/cagliostro-colab-ui/models/VAE/stable_diffusion.vae.pt
Applying optimization: xformers... done.
Textual inversion embeddings loaded(9): bad-artist, bad-artist-anime, bad-hands-5, bad-image-v2-39000, bad_prompt, bad_prompt_version2, EasyNegative, EasyNegativeV2, ng_deepnegative_v1_75t
Textual inversion embeddings skipped(7): nfixer, re-badprompt, Mayng, nrealfixer, rev2-badprompt, wdbadprompt, nartfixer
Model loaded in 4.8s (load weights from disk: 1.6s, create model: 2.7s, load VAE: 0.3s).
Exception ignored in atexit callback: <function kill at 0x7f33233dfd00>
TypeError: kill() missing 1 required positional argument: 'self'

**Comment by Linaqruf** [comment]
I fixed it temporarily by skipping Lycoris extensions when updating. https://github.com/Linaqruf/sd-notebook-collection/commit/5935793265aa05017bd0d0ad6f6f0ad5319dcedd."

Thank you for the report.

**Comment by katsuki-uuu** [comment]
Thank you. It worked fine!
