### ISSUE TITLE
Have a issue when install Cagliostro Colab UI

### ISSUE THREAD

**Issue by Kwhasila** [Linaqruf/sd-notebook-collection#53]
Hello! 
i got a error immediately after mounting drive

Mounting google drive...
Mounted at /content/drive
Set default output path to: /content/drive/MyDrive/cagliostro-colab-ui/outputs
================================================================================
 [-] Current GPU: Tesla T4
 [-] Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
 [-] Torch 2.0.1+cu118
================================================================================
Installing ubuntu dependencies: 100%|██████████| 6/6 [00:04<00:00,  1.37it/s]
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-2-b5ae1d6b59c0>](https://localhost:8080/#) in <cell line: 311>()
    309     print_line(80, color="green")
    310 
--> 311 main()

2 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    522         retcode = process.poll()
    523         if check and retcode:
--> 524             raise CalledProcessError(retcode, process.args,
    525                                      output=stdout, stderr=stderr)
    526     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['apt', 'install', 'libunwind8-dev', '-y']' returned non-zero exit status 100.

**Comment by Linaqruf** [comment]
please try again, I pushed the fix
