### ISSUE TITLE
Colab not working

### ISSUE THREAD

**Issue by relesnx** [Linaqruf/sd-notebook-collection#54]
Today the colab stopped working for me, right of the bat when trying to install Cagliostro Colab UI i get this error

tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

An error occurred: [Errno 2] No such file or directory: 'automatic1111-webui.tar.lz4'
Preparing environment...

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-1-ef977728e131>](https://localhost:8080/#) in <cell line: 311>()
    309     print_line(80, color="green")
    310 
--> 311 main()

2 frames

[/usr/local/lib/python3.10/dist-packages/colablib/utils/config_utils.py](https://localhost:8080/#) in read_config(filename)
     36 
     37     if file_format == "json":
---> 38         with open(filename, "r") as f:
     39             config = json.load(f)
     40     elif file_format == "yaml" or file_format == "yml":

FileNotFoundError: [Errno 2] No such file or directory: '/content/cagliostro-colab-ui/config.json'

**Comment by Linaqruf** [comment]
I pushed the fix a several hours ago
